<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Framework Básico</title>


	<link rel="stylesheet" type="text/css" href="<?php echo $_layoutParams["route_css"]?>/style.css">
	<!--Agregamos la libreria que se encuentra en la carpeta bootstrap-->
	<link rel="stylesheet" type="text/css" href="<?php echo $_layoutParams["route_bootstrap_css"]?>/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="<?php echo $_layoutParams["route_bootstrap_css"]?>/bootstrap-responsive.css">




</head>
<body>
	<div id="container" class="container">
	<header>
		<nav>
			<ul>
				<li><a href="">Inicio</a></li>
				<li><a href="">Servicio</a></li>
				<li><a href="">Productos</a></li>
				<li><a href="">Nosotros</a></li>
				<li><a href="">Contactos</a></li>
			</ul>
		</nav>
		<div class="login"
		<h3>Hola bienvenido a tu sistema<?php echo $_SESSION["username"]; ?></h3>
		<a href="<?php echo APP_URL."/users/logout"; ?>">Salir</a>
	</div>
	</header>

	<!-- <img src="<?php //echo $_layoutParams["route_img"]?>/social.png"> -->
		<!-- //nav>ul>li>*50>a>{Item} -->
