
	</div>
	<footer>
	   <link rel="stylesheet" type="text/css" href="<?php echo $_layoutParams["route_js"]?>/jquery-confirm.css">
	   <script type="text/javascript" src="<?php echo $_layoutParams["route_js"]?>/jquery.min.js"></script>
	    <script type="text/javascript" src="<?php echo $_layoutParams["route_bootstrap_js"]?>/bootstrap.min.js"></script>
	   <script type="text/javascript" src="<?php echo $_layoutParams["route_js"]?>/jquery-confirm.js"></script>
		<script type="text/javascript" src="<?php echo $_layoutParams["route_js"]?>/delete_users.js"></script>	
	</footer>
</body>
    
</html>